!!com.bor.javawebexample.fs.Configuration
dbConfig:
  databaseUrl: jdbc:mysql://localhost:3306/test
  password: '1'
  user: root
jsondataPath: /home/leon/JEExample/jsondata.txt
logFilePath: ./log/log.log
mainDirPath: ./JavaEETest